=== huiishan99/huishan.github/Airsim_rec.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Airsim_rec" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Airsim_rec">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="lhmv9Do/MUiagos7yjF9TA==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACWGa/0Oj8xSJqCizvKMX1MAAAAAAC5/rLS0uVAAAAAAAAAAABBAGkA
cgBzAGkAbQBfAHIAZQBjAAAAAAAAALHj3MGNdYJCgvSVqHBkgc0HAAAAlhmv9Do/
MUiagos7yjF9TFYAZQBoAGkAYwBsAGUATgBhAG0AZQAAAAAAAACrcDTPS/xlTIOh
9FEpPQXWBwAAAJYZr/Q6PzFImoKLO8oxfUxUAGkAbQBlAFMAdABhAG0AcAAAAAAA
AAD3N10kt0fkRrBv5e96qgIGBwAAAJYZr/Q6PzFImoKLO8oxfUxQAE8AUwBfAFgA
AAAAAAAAyvy3LjQp1kmstvEp3Gc78QcAAACWGa/0Oj8xSJqCizvKMX1MUABPAFMA
XwBZAAAAAAAAAMDu4G+eZntOn986OSHsF7kHAAAAlhmv9Do/MUiagos7yjF9TFAA
TwBTAF8AWgAAAAAAAADohtjLgjS/SJEcdmuSU9fSBwAAAJYZr/Q6PzFImoKLO8ox
fUxRAF8AVwAAAAAAAAB9s07B++B5RKSJSgOxNDwWBwAAAJYZr/Q6PzFImoKLO8ox
fUxRAF8AWAAAAAAAAAD/KcCJmqz2T6St2UfpDYCQBwAAAJYZr/Q6PzFImoKLO8ox
fUxRAF8AWQAAAAAAAAALMSlLP1sJSoZMJSATDErzBwAAAJYZr/Q6PzFImoKLO8ox
fUxRAF8AWgAAAAAAAAC0X2p2g5qRRatP0CyloqkNBwAAAJYZr/Q6PzFImoKLO8ox
fUxJAG0AYQBnAGUARgBpAGwAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="VehicleName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="sePcwY11gkKC9JWocGSBzQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="TimeStamp" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="q3A0z0v8ZUyDofRRKT0F1g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="POS_X" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="9zddJLdH5Eawb+XveqoCBg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="POS_Y" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="yvy3LjQp1kmstvEp3Gc78Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="POS_Z" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="wO7gb55me06f3zo5IewXuQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Q_W" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="6IbYy4I0v0iRHHZrklPX0g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Q_X" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="fbNOwfvgeUSkiUoDsTQ8Fg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Q_Y" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="/ynAiZqs9k+krdlH6Q2AkA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Q_Z" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="CzEpSz9bCUqGTCUgEwxK8w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ImageFile" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="tF9qdoOakUWrT9AspaKpDQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="1"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== huiishan99/huishan.github/Airsim_rec.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Airsim_rec.xsd" generated="2022-05-13T14:03:47">
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-134.195</POS_X>
<POS_Y>57.8097</POS_Y>
<POS_Z>-46.1518</POS_Z>
<Q_W>-0.995227</Q_W>
<Q_X>0.00833477</Q_X>
<Q_Y>0.084779</Q_Y>
<Q_Z>0.047616</Q_Z>
<ImageFile>img_Drone_3__0_1650816275331650700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-134.341</POS_X>
<POS_Y>58.6392</POS_Y>
<POS_Z>-46.3004</POS_Z>
<Q_W>-0.998471</Q_W>
<Q_X>0.0070635</Q_X>
<Q_Y>0.0511397</Q_Y>
<Q_Z>0.0197736</Q_Z>
<ImageFile>img_Drone_2__0_1650816275403581500.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-134.528</POS_X>
<POS_Y>59.3469</POS_Y>
<POS_Z>-46.4229</POS_Z>
<Q_W>-0.999374</Q_W>
<Q_X>0.00601652</Q_X>
<Q_Y>0.0328131</Q_Y>
<Q_Z>-0.0117802</Q_Z>
<ImageFile>img_Drone_1__0_1650816275476179400.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-134.787</POS_X>
<POS_Y>60.1235</POS_Y>
<POS_Z>-46.7584</POS_Z>
<Q_W>-0.998479</Q_W>
<Q_X>0.00494226</Q_X>
<Q_Y>0.020578</Q_Y>
<Q_Z>-0.0509031</Q_Z>
<ImageFile>img_Drone_3__0_1650816275550670100.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-134.919</POS_X>
<POS_Y>60.9377</POS_Y>
<POS_Z>-46.9404</POS_Z>
<Q_W>-0.994962</Q_W>
<Q_X>0.00385276</Q_X>
<Q_Y>0.012323</Q_Y>
<Q_Z>-0.0994193</Q_Z>
<ImageFile>img_Drone_2__0_1650816275622272700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-135.089</POS_X>
<POS_Y>61.5983</POS_Y>
<POS_Z>-47.086</POS_Z>
<Q_W>-0.989607</Q_W>
<Q_X>0.00305357</Q_X>
<Q_Y>0.00800394</Q_Y>
<Q_Z>-0.143546</Q_Z>
<ImageFile>img_Drone_1__0_1650816275694118700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-135.333</POS_X>
<POS_Y>62.3278</POS_Y>
<POS_Z>-47.4483</POS_Z>
<Q_W>-0.981311</Q_W>
<Q_X>0.00233898</Q_X>
<Q_Y>0.00506898</Q_Y>
<Q_Z>-0.19235</Q_Z>
<ImageFile>img_Drone_3__0_1650816275763324700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-135.383</POS_X>
<POS_Y>62.8275</POS_Y>
<POS_Z>-47.5599</POS_Z>
<Q_W>-0.974418</Q_W>
<Q_X>0.00189159</Q_X>
<Q_Y>0.0036627</Q_Y>
<Q_Z>-0.224707</Q_Z>
<ImageFile>img_Drone_2__0_1650816275811608300.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-135.541</POS_X>
<POS_Y>63.4456</POS_Y>
<POS_Z>-47.7007</POS_Z>
<Q_W>-0.966084</Q_W>
<Q_X>0.00140484</Q_X>
<Q_Y>0.00243189</Q_Y>
<Q_Z>-0.258213</Q_Z>
<ImageFile>img_Drone_1__0_1650816275880811400.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-135.734</POS_X>
<POS_Y>63.9667</POS_Y>
<POS_Z>-47.9842</POS_Z>
<Q_W>-0.960124</Q_W>
<Q_X>0.0010929</Q_X>
<Q_Y>0.00176407</Q_Y>
<Q_Z>-0.279568</Q_Z>
<ImageFile>img_Drone_3__0_1650816275925789100.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-135.828</POS_X>
<POS_Y>64.6604</POS_Y>
<POS_Z>-48.1336</POS_Z>
<Q_W>-0.95283</Q_W>
<Q_X>0.000756275</Q_X>
<Q_Y>0.00112945</Q_Y>
<Q_Z>-0.303501</Q_Z>
<ImageFile>img_Drone_2__0_1650816276000725800.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-136.013</POS_X>
<POS_Y>65.4034</POS_Y>
<POS_Z>-48.2818</POS_Z>
<Q_W>-0.946246</Q_W>
<Q_X>0.000497496</Q_X>
<Q_Y>0.000696171</Q_Y>
<Q_Z>-0.323448</Q_Z>
<ImageFile>img_Drone_1__0_1650816276070644000.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-136.236</POS_X>
<POS_Y>66.0501</POS_Y>
<POS_Z>-48.5765</POS_Z>
<Q_W>-0.941812</Q_W>
<Q_X>0.000348985</Q_X>
<Q_Y>0.000468237</Q_Y>
<Q_Z>-0.33614</Q_Z>
<ImageFile>img_Drone_3__0_1650816276136387000.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-136.34</POS_X>
<POS_Y>66.8014</POS_Y>
<POS_Z>-48.7108</POS_Z>
<Q_W>-0.937483</Q_W>
<Q_X>0.000225536</Q_X>
<Q_Y>0.000290635</Q_Y>
<Q_Z>-0.34803</Q_Z>
<ImageFile>img_Drone_2__0_1650816276204980100.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-136.49</POS_X>
<POS_Y>67.405</POS_Y>
<POS_Z>-48.8045</POS_Z>
<Q_W>-0.934636</Q_W>
<Q_X>0.000156578</Q_X>
<Q_Y>0.000196438</Q_Y>
<Q_Z>-0.355606</Q_Z>
<ImageFile>img_Drone_1__0_1650816276272957400.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-136.71</POS_X>
<POS_Y>68.0447</POS_Y>
<POS_Z>-49.1031</POS_Z>
<Q_W>-0.932322</Q_W>
<Q_X>0.000108224</Q_X>
<Q_Y>0.000132757</Q_Y>
<Q_Z>-0.361629</Q_Z>
<ImageFile>img_Drone_3__0_1650816276338219700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-136.787</POS_X>
<POS_Y>68.6911</POS_Y>
<POS_Z>-49.2395</POS_Z>
<Q_W>-0.930333</Q_W>
<Q_X>-0.000953846</Q_X>
<Q_Y>0.0026959</Q_Y>
<Q_Z>-0.366704</Q_Z>
<ImageFile>img_Drone_2__0_1650816276399008700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-136.918</POS_X>
<POS_Y>69.2239</POS_Y>
<POS_Z>-49.3498</POS_Z>
<Q_W>-0.928838</Q_W>
<Q_X>-0.00564008</Q_X>
<Q_Y>0.014472</Q_Y>
<Q_Z>-0.37016</Q_Z>
<ImageFile>img_Drone_1__0_1650816276463373500.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-137.157</POS_X>
<POS_Y>69.9557</POS_Y>
<POS_Z>-49.7203</POS_Z>
<Q_W>-0.926632</Q_W>
<Q_X>-0.0158588</Q_X>
<Q_Y>0.0399887</Q_Y>
<Q_Z>-0.373499</Q_Z>
<ImageFile>img_Drone_3__0_1650816276528445100.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-137.218</POS_X>
<POS_Y>70.5676</POS_Y>
<POS_Z>-49.8821</POS_Z>
<Q_W>-0.924497</Q_W>
<Q_X>-0.0242107</Q_X>
<Q_Y>0.0606651</Q_Y>
<Q_Z>-0.375552</Q_Z>
<ImageFile>img_Drone_2__0_1650816276595599200.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-137.361</POS_X>
<POS_Y>71.1988</POS_Y>
<POS_Z>-50.057</POS_Z>
<Q_W>-0.921183</Q_W>
<Q_X>-0.0364268</Q_X>
<Q_Y>0.0905843</Q_Y>
<Q_Z>-0.376681</Q_Z>
<ImageFile>img_Drone_1__0_1650816276660287700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-137.564</POS_X>
<POS_Y>71.839</POS_Y>
<POS_Z>-50.421</POS_Z>
<Q_W>-0.917871</Q_W>
<Q_X>-0.0462254</Q_X>
<Q_Y>0.114369</Q_Y>
<Q_Z>-0.377221</Q_Z>
<ImageFile>img_Drone_3__0_1650816276726575200.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-137.592</POS_X>
<POS_Y>72.4281</POS_Y>
<POS_Z>-50.5903</POS_Z>
<Q_W>-0.916287</Q_W>
<Q_X>-0.0497111</Q_X>
<Q_Y>0.122604</Q_Y>
<Q_Z>-0.378042</Q_Z>
<ImageFile>img_Drone_2__0_1650816276794072700.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-137.731</POS_X>
<POS_Y>73.1384</POS_Y>
<POS_Z>-50.8044</POS_Z>
<Q_W>-0.92024</Q_W>
<Q_X>-0.0333609</Q_X>
<Q_Y>0.0826027</Q_Y>
<Q_Z>-0.38108</Q_Z>
<ImageFile>img_Drone_1__0_1650816276860557100.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-137.914</POS_X>
<POS_Y>73.7905</POS_Y>
<POS_Z>-51.18</POS_Z>
<Q_W>-0.921855</Q_W>
<Q_X>-0.0227793</Q_X>
<Q_Y>0.0565807</Q_Y>
<Q_Z>-0.382705</Q_Z>
<ImageFile>img_Drone_3__0_1650816276929210000.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-137.941</POS_X>
<POS_Y>74.4556</POS_Y>
<POS_Z>-51.39</POS_Z>
<Q_W>-0.922665</Q_W>
<Q_X>-0.015142</Q_X>
<Q_Y>0.0376684</Q_Y>
<Q_Z>-0.38346</Q_Z>
<ImageFile>img_Drone_2__0_1650816276989194800.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-138.031</POS_X>
<POS_Y>75.0051</POS_Y>
<POS_Z>-51.5567</POS_Z>
<Q_W>-0.923653</Q_W>
<Q_X>-0.0107373</Q_X>
<Q_Y>0.0265546</Q_Y>
<Q_Z>-0.382159</Q_Z>
<ImageFile>img_Drone_1__0_1650816277050581600.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-138.221</POS_X>
<POS_Y>75.7584</POS_Y>
<POS_Z>-51.9894</POS_Z>
<Q_W>-0.92634</Q_W>
<Q_X>-0.00695264</Q_X>
<Q_Y>0.0167727</Q_Y>
<Q_Z>-0.376252</Q_Z>
<ImageFile>img_Drone_3__0_1650816277116888300.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-138.215</POS_X>
<POS_Y>76.256</POS_Y>
<POS_Z>-52.1388</POS_Z>
<Q_W>-0.929306</Q_W>
<Q_X>-0.00522893</Q_X>
<Q_Y>0.0122495</Q_Y>
<Q_Z>-0.36907</Q_Z>
<ImageFile>img_Drone_2__0_1650816277173431900.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-138.306</POS_X>
<POS_Y>76.8363</POS_Y>
<POS_Z>-52.3255</POS_Z>
<Q_W>-0.93389</Q_W>
<Q_X>-0.00375055</Q_X>
<Q_Y>0.00839301</Q_Y>
<Q_Z>-0.357443</Q_Z>
<ImageFile>img_Drone_1__0_1650816277234048200.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-138.457</POS_X>
<POS_Y>77.3533</POS_Y>
<POS_Z>-52.6672</POS_Z>
<Q_W>-0.938318</Q_W>
<Q_X>-0.00286034</Q_X>
<Q_Y>0.00612356</Q_Y>
<Q_Z>-0.345706</Q_Z>
<ImageFile>img_Drone_3__0_1650816277285446500.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_2</VehicleName>
<POS_X>-138.467</POS_X>
<POS_Y>77.9803</POS_Y>
<POS_Z>-52.8854</POS_Z>
<Q_W>-0.943553</Q_W>
<Q_X>-0.00202576</Q_X>
<Q_Y>0.0041148</Q_Y>
<Q_Z>-0.331189</Q_Z>
<ImageFile>img_Drone_2__0_1650816277344053800.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_1</VehicleName>
<POS_X>-138.56</POS_X>
<POS_Y>78.5892</POS_Y>
<POS_Z>-53.102</POS_Z>
<Q_W>-0.947759</Q_W>
<Q_X>-0.0014211</Q_X>
<Q_Y>0.00276257</Q_Y>
<Q_Z>-0.318973</Q_Z>
<ImageFile>img_Drone_1__0_1650816277408957400.png</ImageFile>
</Airsim_rec>
<Airsim_rec>
<VehicleName>Drone_3</VehicleName>
<POS_X>-138.724</POS_X>
<POS_Y>79.2006</POS_Y>
<POS_Z>-53.5029</POS_Z>
<Q_W>-0.950909</Q_W>
